#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Tue Apr 21 16:28:12 2015
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame1.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, wx.ID_ANY, _("Swerver"), style=wx.ALIGN_CENTRE)
        self.startButton = wx.Button(self, wx.ID_ANY, _("Start"))
        self.label_5 = wx.StaticText(self, wx.ID_ANY, _("\nServer Status\n"), style=wx.ALIGN_CENTRE)
        self.stopButton = wx.Button(self, wx.ID_ANY, _("Stop"))
        self.statusText = wx.StaticText(self, wx.ID_ANY, _("\nStatus\n"), style=wx.ALIGN_CENTRE)
        self.restartButton = wx.Button(self, wx.ID_ANY, _("Restart"))
        self.goButton = wx.Button(self, wx.ID_ANY, _("Go to Server"))
        self.uploadButton = wx.Button(self, wx.ID_ANY, _("Upload"))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame1.__set_properties
        self.SetTitle(_("frame_2"))
        self.SetSize((459, 411))
        self.label_1.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_5.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.statusText.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame1.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(3, 2, 0, 0)
        sizer_2.Add(self.label_1, 0, wx.ALL | wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 10)
        grid_sizer_1.Add(self.startButton, 0, wx.ALL | wx.EXPAND, 10)
        grid_sizer_1.Add(self.label_5, 0, wx.ALL | wx.EXPAND, 10)
        grid_sizer_1.Add(self.stopButton, 0, wx.ALL | wx.EXPAND, 10)
        grid_sizer_1.Add(self.statusText, 0, wx.ALL | wx.EXPAND, 10)
        grid_sizer_1.Add(self.restartButton, 0, wx.ALL | wx.EXPAND, 10)
        grid_sizer_1.Add(self.goButton, 0, wx.ALL | wx.EXPAND, 10)
        sizer_2.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        sizer_2.Add(self.uploadButton, 0, wx.ALL | wx.EXPAND, 10)
        self.SetSizer(sizer_2)
        self.Layout()
        # end wxGlade

# end of class MyFrame1
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    mainwindow = (None, wx.ID_ANY, "")
    app.SetTopWindow(mainwindow)
    mainwindow.Show()
    app.MainLoop()