#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Thu Apr 16 14:39:21 2015
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.Title2Label = wx.StaticText(self, wx.ID_ANY, _("Welcome To Swerver!"), style=wx.ALIGN_CENTRE)
        self.StartButton = wx.Button(self, wx.ID_ANY, _("Start"))
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.StopButton = wx.Button(self, wx.ID_ANY, _("Stop"))
        self.DoingThingsLabel = wx.StaticText(self, wx.ID_ANY, _("  Click to\nDo Things"), style=wx.ALIGN_CENTRE)
        self.RestartButton = wx.Button(self, wx.ID_ANY, _("Restart"))
        self.GoToButton = wx.Button(self, wx.ID_ANY, _("Go To"))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("frame_1"))
        self.SetSize((506, 414))
        self.Title2Label.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.BOLD, 1, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(3, 2, 0, 0)
        sizer_1.Add(self.Title2Label, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.StartButton, 0, wx.ALL | wx.EXPAND, 10)
        grid_sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.StopButton, 0, wx.ALL | wx.EXPAND, 10)
        grid_sizer_1.Add(self.DoingThingsLabel, 0, wx.ALL | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 10)
        grid_sizer_1.Add(self.RestartButton, 0, wx.ALL | wx.EXPAND, 10)
        grid_sizer_1.Add(self.GoToButton, 0, wx.ALL | wx.EXPAND, 10)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class MyFrame

class MyFrame1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame1.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.Title1Label = wx.StaticText(self, wx.ID_ANY, _("Swerver"), style=wx.ALIGN_CENTRE)
        self.Logo = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/michael/Pictures/Tire.jpg", wx.BITMAP_TYPE_ANY))
        self.StartGuiButton = wx.Button(self, wx.ID_ANY, _("Start Swerver"))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame1.__set_properties
        self.SetTitle(_("frame_2"))
        self.SetSize((484, 443))
        self.Title1Label.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.BOLD, 1, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame1.__do_layout
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_4.Add(self.Title1Label, 0, wx.ALL | wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL, 10)
        sizer_4.Add(self.Logo, 0, wx.ALL | wx.EXPAND, 10)
        sizer_4.Add(self.StartGuiButton, 0, wx.ALL | wx.EXPAND, 10)
        self.SetSizer(sizer_4)
        self.Layout()
        # end wxGlade

# end of class MyFrame1
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    ActualGuiFrame = MyFrame(None, wx.ID_ANY, "")
    app.SetTopWindow(ActualGuiFrame)
    ActualGuiFrame.Show()
    app.MainLoop()